---
title: |
  | When to use spatially-explicit fishery stock assessments:  
  | is good data good enough?
author:
  - name: Katelyn M Bosley
    email: Katelyn.bosley@noaa.gov
    affiliation: NOAA-Fisheries NWFSC Newport
    footnote: Corresponding Author
  - name: Daniel Goethel
    email: Daniel.Goethel@noaa.gov
    affiliation: NOAA-Fisheries SEFSC Miami
  - name: Aaron Berger
    email: Aaron.Berger@noaa.gov
    affiliation: NOAA-Fisheries NWFSC Newport
  - name: Amy Schueller
    email: Amy.Schueller@noaa.gov
    affiliation: NOAA-Fisheries SEFSC Beaufort
  - name: Dana Hanselman
    email: Dana.Hanselman@noaa.gov
    affiliation: NOAA-Fisheries AKFSC   
  - name: Brian Langseth
    email: Brian.Langseth@noaa.gov
    affiliation: NOAA-Fisheries PIFSC
  - name: Jonathan Deroba
    email: Jonathan.Deroba@noaa.gov
    affiliation: NOAA-Fisheries NEFSC
    
address:
  - code: NOAA-Fisheries NWFSC Newport
    address: Fisheries Resource and Monitoring Division, Northwest Fisheries Science Center, NMFS-NOAA, 2032 S.E. OSU Drive, Newport, OR 97365, USA 
  - code: NOAA-Fisheries SEFSC Miami
    address: Sustainable Fisheries Division, Southeast Fisheries Science Center, NMFS-NOAA, 75 Virginia Beach Drive, Miami, FL 33133, USA
  - code: NOAA-Fisheries SEFSC Beaufort
    address: National Marine Fisheries Service, Southeast Fisheries Science Center, Beaufort Laboratory, 101 Pivers Island Road, Beaufort, NC 28516, USA  
  - code: NOAA-Fisheries AKFSC
    address: Auke Bay Laboratories, Alaska Fisheries Science Center, National Marine Fisheries Service, NOAA, 17109 Point Lena Loop Road, Juneau, AK 99801, USA  
  - code: NOAA-Fisheries PIFSC
    address: Pacific Islands Fisheries Science Center, NMFS-NOAA, 1845 Wasp Blvd., Bldg. 176, Honolulu HI, 96818, USA
  - code: NOAA-Fisheries NEFSC
    address: North East Fisheries Science Center, NMFS-NOAA, 166 Water St., Woods Hole MA, 02543, USA 
    
abstract: This is the abstract.

  It consists of two paragraphs.
  
fig_caption: true
keep_tex: true
bibliography: library.bib
citation_package: natbib
csl: CJFAS.csl
output: rticles::elsevier_article
---

# INTRODUCTION

This is a test of the citation system [@Carruthers2014]. I can change the citation format to anything we want.

# METHODS



# RESULTS


*Practice Table* 

\begin{center}
Table 1: Manual table
\end{center}

| Column 1 | Column 2  | Column 3|
|----------|-----------|---------|
| mean     | SD        | _n_=7   |


```{r,echo = F, results = 'asis', warning = F , message = F,eval = T}
library(pander)
x=seq(1,100,by = 1)
y.rand=rnorm(100,0,9)
y = seq(1,100)+y.rand
test<-lm(y~x)

panderOptions("digits", 2)
pander(test)
```

*Practice figure*

\begin{center}
Figure 1: Random Linear Model
\end{center}
```{r, echo = F, results = 'asis', warning = F, message = F,eval = T, fig.align='center', fig.height=5,fig.width=5}
plot(x,y, bg = "red", cex = 1.2, pch = 21, col = "black")
abline(test,col = "red",lty = 2)
abline(1,1,col  = "black")
```

# DISCUSSION

# CONCLUSIONS

# ACKNOWLEDGEMENTS

# LITERATURE CITED





